# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
# default: &default
#   adapter: mysql2
#   encoding: utf8mb4
#   collation: utf8mb4_unicode_ci
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
#   username: <%= ENV.fetch("DB_USERNAME", "root") %>
#   password: <%= ENV.fetch("DB_PASSWORD", "password") %>
#   host: <%= ENV.fetch("DB_HOST", "localhost") %>

# development:
#   <<: *default
#   database: enterprises_development

# test:
#   <<: *default
#   database: enterprises_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>